name: TrulyRevampedPrison
version: '${project.version}'
main: me.striker2421.trulyrevampedprison.Prison
api-version: 1.18
authors: [ Striker2421 ]
description: This is the most advanced prison plugin you will feast your eyes on.
